name: Prepare workspace
description: Sets up Node.js, Pnpm, and installs dependencies

runs:
    using: composite
    steps:
        - name: Set up Pnpm
          uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
          with:
              cache: true
              require-lockfile: true
              runtime: node
